# https://stackoverflow.com/a/15650828/2298061

getPackages <- function(packs) {
  packages <- unlist(
    tools::package_dependencies(
      packs,
      available.packages(),
      which = c("Depends", "Imports"),
      recursive = TRUE
    )
  )
  packages <- union(packs, packages)
  packages
}

packages <- getPackages(
  c(
    "assertthat",
    "base64enc",
    "bindr",
    "bindrcpp",
    "bit64",
    "bit",
    "blob",
    "cli",
    "colorspace",
    "crayon",
    "crosstalk",
    "data.table",
    "DBI",
    "digest",
    "dplyr",
    "DT",
    "fansi",
    "ggplot2",
    "glue",
    "gridExtra",
    "gtable",
    "htmltools",
    "htmlwidgets",
    "httpuv",
    "jsonlite",
    "labeling",
    "later",
    "lattice",
    "lazyeval",
    "leaflet",
    "logging",
    "magrittr",
    "markdown",
    "MASS",
    "Matrix",
    "memoise",
    "mgcv",
    "mime",
    "munsell",
    "nlme",
    "openxlsx",
    "pillar",
    "pkgconfig",
    "plyr",
    "png",
    "prettyunits",
    "promises",
    "purrr",
    "R6",
    "raster",
    "RColorBrewer",
    "Rcpp",
    "reshape2",
    "rlang",
    "RODBC",
    "RSQLite",
    "scales",
    "shiny",
    "shinycssloaders",
    "shinydashboard",
    "shinydashboardPlus",
    "shinyjs",
    "shinyTime",
    "skimr",
    "sourcetools",
    "sp",
    "stringi",
    "stringr",
    "tibble",
    "tidyselect",
    "utf8",
    "viridis",
    "viridisLite",
    "withr",
    "xtable",
    "yaml",
    "zip"
   )
)

download.packages(packages,
                  destdir = getwd(),
                  type    = "win.binary")
